name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug secrets
        run: |
          echo "${{ secrets.SERVER_HOST }}" | base64
          echo "${{ secrets.SERVER_USER }}" | base64
          echo "${{ secrets.SERVER_PASS }}" | base64

      - name: Clean target directory on server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          curl_insecure: true
          debug: true
          port: 22
          script: |
            rm -rf /.esmaili/projects/backend
            mkdir -p /.esmaili/projects/backend

      - name: Copy code to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          source: "./"
          target: "/.esmaili/projects/backend"
          rsync: true

      - name: Build docker image on server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |
            cd /.esmaili/projects/backend
            VERSION=$(jq -r .version package.json)
            echo "Building atrsun-crm:${VERSION}"
            docker build -t atrsun-crm:${VERSION} .
